### ISSUE TITLE
Remove the custom domain if you don't have a domain name

### ISSUE THREAD

**Issue by HPLZH** [aso-ljh/mypage#1]
If you don't have a domain name, remove the custom domain in the settings of this repo.

The CNAME file in your repo looks strange. We know that www.baidu.com belongs to the Baidu company, not you.

Follow the picture to remove the custom domain.

If you have a domain name and want to use it, read [this](https://docs.github.com/cn/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages) on GitHub Docs first.

![网页捕获_8-9-2022_15398_github com](https://user-images.githubusercontent.com/98673025/189069868-67090b7a-1b88-455e-8443-8f53977e4d9c.jpeg)

**Comment by HPLZH** [comment]
If you didn't set the custom domain and added the CNAME file manually, please delete that file.

**Comment by aso-ljh** [comment]
In fact , I do this by trying again and again , so can you talk clearly , or you help me do this , 李子晗先生。(说实话，为什么不用中文呢？)
