### ISSUE TITLE
更改图片的储存方式

### ISSUE THREAD

**Issue by HPLZH** [aso-ljh/mypage#2]
如果在仓库中直接存储JPEG图片，会占用大量空间，而仓库大小是有限制的。（你的照片的大小可达2MB/张）
如果要在页面中插入照片，推荐使用图床，不过将图片以GIF格式储存也可以节省大量空间。

**Comment by aso-ljh** [comment]
很不错的建议，所以图床是什么？












赖嘉宏
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月30日(周日) 中午1:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [aso-ljh/mypage] 更改图片的储存方式 (Issue #2)




 
如果在仓库中直接存储JPEG图片，会占用大量空间，而仓库大小是有限制的。（你的照片的大小可达2MB/张）
 如果要在页面中插入照片，推荐使用图床，不过将图片以GIF格式储存也可以节省大量空间。

**Comment by HPLZH** [comment]
请自行搜索

**Comment by aso-ljh** [comment]
目前来看，后者比较合适，不过转出转入过程比较复杂，因为原先保存的原图丢了。
让我慢慢干好了。
谢谢。

**Comment by HPLZH** [comment]
另外，你好像把一个视频也放入仓库中了。
图片和视频建议不要存太多。

**Comment by aso-ljh** [comment]
那好像是一个意外，现在已经解决了。
